version: '3.7'
services:
  postgres:
    container_name: postgres
    image: postgres:11.1
    networks:
      - internal_network
    ports:
      - "5432"
  web:
    build: .
    container_name: web
    env_file:
      - .env
    environment:
      DB_HOST: postgres
    networks:
      - internal_network
    command: |
      bash -c "
      rm -f tmp/pids/server.pid &&
      (bundle check || bundle install) &&
      bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/reserva2
    ports:
      - "3000:3000"
    depends_on:
      - postgres

networks:
  internal_network:
