default: &default
  adapter: postgresql
  encoding: unicode
  pool: 15
  host: <%= ENV['DB_HOST'] || 'localhost' %>
  port: <%= ENV['DB_PORT'] || 5432 %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>

development:
  <<: *default
  database: reserva2_dev

test:
  <<: *default
  database: reserva2_test

production:
  <<: *default
  database: reserva2_prod
